# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

#MAKEOPTS for a 12 threaded processor
MAKEOPTS="-j3 -l7"

#Force all packages to run with --ask --verbose for convenience 
#Parallel compiling is set with the ideal of ensuring roughly decent to usable responsiveness while compiling runs
# -ask-enter invalid - Set for sanity checking
# --changed-deps - forcing rebuild with changes in dependencies is set for live ebuild use and for avoiding potential issues with overlay useage
# --keep-going=y - I honestly dont know why this isnt just the default same goes for --tree --unordered-display
# --deep (-D) --newuse (-N) - I think its much better to have emerge install everything in a closer manner to how it would be if it was installed during system installation
EMERGE_DEFAULTS_OPTS="-a --ask-enter-invalid --D -N --changed-deps  --keep-going=y --tree --unordered-display --with-bdeps=y --backtrack=30 -v --jobs=3 --load-average=7.5"

# System responsiveness adjustments in line with parallel compiling settings
PORTAGE_NICENESS="15"
PORTAGE_IONICE_COMMAND="ionice -c 3 -p \${PID}"

# This sets the language of build output to English.
LC_MESSAGES=C.UTF-8

# unmasking packages marked as testing
ACCEPT_KEYWORDS="~amd64"

#Gentoo dist mirrors
GENTOO_MIRRORS="https://callisto.gb.ext.planetunix.net/pub/gentoo/ https://www.mirrorservic>

ACCEPT_LICENSE="*"
